### ISSUE TITLE
License cannot be saved if the WordPress installation is done in the sub directory

### ISSUE THREAD

**Issue by tremidkhar** [rtCamp/transcoder#234] opened 2021-03-23 06:43 UTC
If WordPress is installed on the sub directory (example.com/sub) instead of the main directory (example.com). Then, when trying to insert and save the license it got redirect to the main site without saving the license.

_Note; This is not a multi-site installation_

**Comment by pooja-muchandikar** [comment] 2021-03-23 09:36
Checked develop branch and the issue is fixed, able to add/save keys without any redirection.

**Comment by pooja-muchandikar** [comment] 2021-04-13 12:14
Fixed and released with `v1.3.3.`

**Closed by pooja-muchandikar** 2021-04-13 12:14 UTC
